### PR TITLE
[WIP]: change outputhandler.handler to read from script than from text

### PR DESCRIPTION
**Pull request by kvprasoon**
@JamesWTruher @theJasonHelmick 
When you have time, please have a look at this PR

json will look like this
```
"OutputHandlers":[
        {
            "ParameterSetName":"Default",
            "Handler": "c:\\temp\\script1.ps1"
        },
        {
            "ParameterSetName":"Summary",
            "Handler":"c:\\temp\\script2.ps1"
        }
    ],
```

### CODE REVIEW

**Comment by JamesWTruher** [comment]
thanks for this, but my plan is to allow for function, script, and inline output handlers. Scripts will be packaged with the module and scripts will be inlined into the module. The schema has to handle the 3 different types of handlers. I'll be getting to this as soon as I can, but the schema as you propose isn't quite flexible enough for my plans.

**Comment by kvprasoon** [comment]
Allowing functions is a cool idea. But is it like referring function name with script name, similar to `scriptname:FunctionName` ?

**Comment by kvprasoon** [comment]
@JamesWTruher will it be possible to share the thoughts you have on how to have different types of handler. I would like to try those out.

**Comment by JamesWTruher** [comment]
@kvprasoon I'm closing this as we have this functionality in preview 4

**Comment by kvprasoon** [comment]
Thanks @JamesWTruher , couldn't get much time to explore the latest versions.

**Pull request closed without merging**
